sudo: required
language: generic

services:
- docker
- docker-compose

script:
  - docker build --tag ${REGISTRY_USERNAME}/swagger-codegen-npm-publish --tag ${REGISTRY_USERNAME}/swagger-codegen-npm-publish:latest --tag ${REGISTRY_USERNAME}/swagger-codegen-npm-publish:$(date "+%d-%m-%Y_%H-%M-%S") .
  - docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
  - docker push ${REGISTRY_USERNAME}/swagger-codegen-npm-publish